# For Loops Coding

In [7]:
suits = ['hearts', 'clubs', 'diamonds', 'spades']

In [11]:
for s in suits:
 print(s)

hearts
clubs
diamonds
spades

In [9]:
for s in suits:
 word = s[0].upper()
 print(f"{word} = {s}")

H = hearts
C = clubs
D = diamonds
S = spades

In [13]:
for s in suits:
 print(f"{s[0].upper()} = {s}")

H = hearts
C = clubs
D = diamonds
S = spades

In [14]:
s

'spades'

In [15]:
for i in range(1,11,2):
    print(i)

1
3
5
7
9

In [16]:
for i in range(2,11,2):
    print(i)

2
4
6
8
10

In [ ]:
l=list(range(2,10,2))
l

[2, 4, 6, 8, 10]

In [20]:
for i in range(3):
    for j in range(3):
        print(f"i={i}, j={j}")
    print('-' * 10)

i=0, j=0
i=0, j=1
i=0, j=2
----------
i=1, j=0
i=1, j=1
i=1, j=2
----------
i=2, j=0
i=2, j=1
i=2, j=2
----------

In [39]:
print('-' * 6, f"TABLE: {1}",'-' * 6)
for i in range(1,10+1):
    for j in range(1,10+1):
        print(f"{i} x {j} =",  (i)*(j))
    print('-' * 6, f"TABLE: {i+1}",'-' * 6)

------ TABLE: 1 ------
1 x 1 = 1
1 x 2 = 2
1 x 3 = 3
1 x 4 = 4
1 x 5 = 5
1 x 6 = 6
1 x 7 = 7
1 x 8 = 8
1 x 9 = 9
1 x 10 = 10
------ TABLE: 2 ------
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20
------ TABLE: 3 ------
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30
------ TABLE: 4 ------
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
4 x 10 = 40
------ TABLE: 5 ------
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50
------ TABLE: 6 ------
6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
6 x 10 = 60
------ TABLE: 7 ------
7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70
------ TABLE: 8 ------
8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
8 x 10 = 80
------ TABLE: 9 ------
9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81
9 x 10 = 90
------ TABLE: 10 ------
10 x 1 = 10
10 x 2 = 20
10 x 3 = 30
10 x 4 = 40
10 x 5 = 50
10 x 6 = 60
10 x 7 = 70
10 x 8 = 80
10 x 9 = 90
10 x 10 = 100
------ TABLE: 11 ------

In [40]:
m = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [43]:
for row_index in range(3):
    for col_index in range(3):
        print(f"[{row_index}, {col_index}] = {m[row_index][col_index]}")

[0, 0] = 1
[0, 1] = 2
[0, 2] = 3
[1, 0] = 4
[1, 1] = 5
[1, 2] = 6
[2, 0] = 7
[2, 1] = 8
[2, 2] = 9

In [44]:
for row_index in range(len(m)):
    for col_index in range(len(m[row_index])):
        print(f"[{row_index}, {col_index}] = {m[row_index][col_index]}")

[0, 0] = 1
[0, 1] = 2
[0, 2] = 3
[1, 0] = 4
[1, 1] = 5
[1, 2] = 6
[2, 0] = 7
[2, 1] = 8
[2, 2] = 9

In [46]:
m = [
    [0,1],
    [2,3,4,5,6],
    [7,8,9],
    [10]
]

In [47]:
for row_index in range(len(m)):
    for col_index in range(len(m[row_index])):
        print(f"[{row_index}, {col_index}] = {m[row_index][col_index]}")

[0, 0] = 0
[0, 1] = 1
[1, 0] = 2
[1, 1] = 3
[1, 2] = 4
[1, 3] = 5
[1, 4] = 6
[2, 0] = 7
[2, 1] = 8
[2, 2] = 9
[3, 0] = 10

In [ ]:
n=5
matrix=[]

for row_index in range(n):
    row=[]
    for col_index in range(n):
        if row_index == col_index:
            row.append(1)
        else:
            row.append(0)
    matrix.append(row)

In [51]:
matrix

[[1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 1]]

In [52]:
data=[10,20,30]

In [53]:
enumerate(data)

In [54]:
list(enumerate(data))

[(0, 10), (1, 20), (2, 30)]

In [55]:
for t in enumerate(data):
    idx, el = t
    print(idx, el)

0 10
1 20
2 30

In [56]:
for idx, el in enumerate(data):
    print(idx, el)

0 10
1 20
2 30

In [60]:
for row in m:
    for col in row:
        print(col)

0
1
2
3
4
5
6
7
8
9
10

In [63]:
n = [
    [0,1],
    [2,3,4,5,6],
    [7,8,9],
    [10]
]

In [64]:
for row in n:
    for col in row:
        print(col)

0
1
2
3
4
5
6
7
8
9
10

In [71]:
data=[10.5,11.2,9.8,None,11.5,None]

In [72]:
count=0
total=0

In [74]:
for i in range(len(data)):
    if data[i] is not None:
        count = count + 1
        total= total + data[i]

average = total/count 
average

10.75

In [89]:
data=[10.5,11.2,9.8,None,11.5,None]

In [90]:
l=[]

In [91]:
for i in data:
     if i is None:
          continue
     else :
          l.append(i)
print(l)

[10.5, 11.2, 9.8, 11.5]

In [118]:
d=[10.5,11.2,9.8,None,11.5,None]

In [119]:
z=[]

In [142]:
print([i for i in d if i != None])

[10.5, 11.2, 9.8, 11.5]

In [143]:
a="abc:<def;]ghi00"

In [144]:
print([i for i in a if a != ":<;]00"])

['a', 'b', 'c', ':', '<', 'd', 'e', 'f', ';', ']', 'g', 'h', 'i', '0', '0']

In [149]:
print([i for i in a if i not in ":<;]00"])

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']

In [169]:
t=(1,2,0,3,[4,0,5],"aero",0)

In [173]:
m= [i for i in t if i != 0]

In [172]:
m[3].remove(0)
print(m)

[1, 2, 3, [4, 5], 'aero']

In [174]:
for item in m:
    if isinstance(item, list):
        while 0 in item:
            item.remove(0)

In [175]:
print(m)

[1, 2, 3, [4, 5], 'aero']

In [177]:
for item in m:
    if isinstance(item,list):
        while 0 in item:
            m.remove(0)

ModuleNotFoundError: No module named 'pandas'

In [183]:
%pip install pandas

^C
Note: you may need to restart the kernel to use updated packages.

The value specified in an AutoRun registry key could not be parsed.
The value specified in an AutoRun registry key could not be parsed.
  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'c:\Users\sumair\AppData\Local\Programs\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

Collecting pandas
  Using cached pandas-3.0.5-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\sumair\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\sumair\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\sumair\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\sumair\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.5-cp314-cp314-win_amd64.whl (10.0 MB)
Installing collected packages: pandas
Successfully installed pandas-3.0.5
Collecting pandas
  Downloading pandas-3.0.5-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy>=2.3.3 (from pandas)
  Using cached numpy-2.5.1-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\sumair\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in C:\Users\sumair\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp314-cp314-win_amd64.whl (10.0 MB)
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/10.0 MB ? eta -:--:--
   -- ------------------------------------- 0.5/10.0 MB 1.2 MB/s eta 0:00:08
   -- ------------------------------------- 0.5/10.0 MB 1.2 MB/s eta 0:00:08
   -- ------------------------------------- 0.5/10.0 MB 1.2 MB/s eta 0:00:08
   -- ------------------------------------- 0.5/10.0 MB 1.2 MB/s eta 0:00:08
   -- ------------------------------------- 0.5/10.0 MB 1.2 MB/s eta 0:00:08
   -- ------------------------------------- 0.5/10.0 MB 1.2 MB/s eta 0:00:08
   -- ------------------------------------- 0.5/10.0 MB 1.2 MB/s eta 0:00:08
   --- ------------------------------------ 0.8/10.0 MB 312.0 kB/s eta 0:00:30
   --- ------------------------------------ 0.8/10.0 MB 312.0 kB/s eta 0:00:30
   --- ------------------------------------ 0.8/10.0 MB 312.0 kB/s eta 0:00:30
   --- ------------------------------------ 0.8/10.0 MB 312.0 kB/s eta 0:00:30
   --- ------------------------------------ 0.8/10.0 MB 312.0 kB/s eta 0:00:30
   --- ------------------------------------ 0.8/10.0 MB 312.0 kB/s eta 0:00:30
   ---- ----------------------------------- 1.0/10.0 MB 267.6 kB/s eta 0:00:34
   ---- ----------------------------------- 1.0/10.0 MB 267.6 kB/s eta 0:00:34
   ---- ----------------------------------- 1.0/10.0 MB 267.6 kB/s eta 0:00:34
   ---- ----------------------------------- 1.0/10.0 MB 267.6 kB/s eta 0:00:34
   ----- ---------------------------------- 1.3/10.0 MB 288.4 kB/s eta 0:00:30
   ----- ---------------------------------- 1.3/10.0 MB 288.4 kB/s eta 0:00:30
   ------ --------------------------------- 1.6/10.0 MB 326.2 kB/s eta 0:00:26
   ------- -------------------------------- 1.8/10.0 MB 363.2 kB/s eta 0:00:23
   ------- -------------------------------- 1.8/10.0 MB 363.2 kB/s eta 0:00:23
   -------- ------------------------------- 2.1/10.0 MB 393.6 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/10.0 MB 393.6 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/10.0 MB 393.6 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/10.0 MB 393.6 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/10.0 MB 393.6 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/10.0 MB 393.6 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/10.0 MB 393.6 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/10.0 MB 393.6 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/10.0 MB 393.6 kB/s eta 0:00:20
   --------- ------------------------------ 2.4/10.0 MB 319.0 kB/s eta 0:00:24
   --------- ------------------------------ 2.4/10.0 MB 319.0 kB/s eta 0:00:24
   ---------- ----------------------------- 2.6/10.0 MB 335.5 kB/s eta 0:00:22
   ---------- ----------------------------- 2.6/10.0 MB 335.5 kB/s eta 0:00:22
   ----------- ---------------------------- 2.9/10.0 MB 353.2 kB/s eta 0:00:21
   ----------- ---------------------------- 2.9/10.0 MB 353.2 kB/s eta 0:00:21
   ----------- ---------------------------- 2.9/10.0 MB 353.2 kB/s eta 0:00:21
   ----------- ---------------------------- 2.9/10.0 MB 353.2 kB/s eta 0:00:21
   ----------- ---------------------------- 2.9/10.0 MB 353.2 kB/s eta 0:00:21
   ------------ --------------------------- 3.1/10.0 MB 346.5 kB/s eta 0:00:20
   ------------- -------------------------- 3.4/10.0 MB 363.0 kB/s eta 0:00:19
   ------------- -------------------------- 3.4/10.0 MB 363.0 kB/s eta 0:00:19
   -------------- ------------------------- 3.7/10.0 MB 378.8 kB/s eta 0:00:17
   --------------- ------------------------ 3.9/10.0 MB 393.0 kB/s eta 0:00:16
   --------------- ------------------------ 3.9/10.0 MB 393.0 kB/s eta 0:00:16
   --------------- ------------------------ 3.9/10.0 MB 393.0 kB/s eta 0:00:16
   --------------- ------------------------ 3.9/10.0 MB 393.0 kB/s eta 0:00:16
   --------------- ------------------------ 3.9/10.0 MB 393.0 kB/s eta 0:00:16
   --------------- ------------------------ 3.9/10.0 MB 393.0 kB/s eta 0:00:16
   --------------- ------------------------ 3.9/10.0 MB 393.0 kB/s eta 0:00:16
   --------------- ------------------------ 3.9/10.0 MB 393.0 kB/s eta 0:00:16
   --------------- ------------------------ 3.9/10.0 MB 393.0 kB/s eta 0:00:16
   --------------- ------------------------ 3.9/10.0 MB 393.0 kB/s eta 0:00:16
   --------------- ------------------------ 3.9/10.0 MB 393.0 kB/s eta 0:00:16
   --------------- ------------------------ 3.9/10.0 MB 393.0 kB/s eta 0:00:16
   --------------- ------------------------ 3.9/10.0 MB 393.0 kB/s eta 0:00:16
   --------------- ------------------------ 3.9/10.0 MB 393.0 kB/s eta 0:00:16
   --------------- ------------------------ 3.9/10.0 MB 393.0 kB/s eta 0:00:16
   --------------- ------------------------ 3.9/10.0 MB 393.0 kB/s eta 0:00:16
   --------------- ------------------------ 3.9/10.0 MB 393.0 kB/s eta 0:00:16
   --------------- ------------------------ 3.9/10.0 MB 393.0 kB/s eta 0:00:16
   --------------- ------------------------ 3.9/10.0 MB 393.0 kB/s eta 0:00:16
   --------------- ------------------------ 3.9/10.0 MB 393.0 kB/s eta 0:00:16
   ---------------- ----------------------- 4.2/10.0 MB 294.4 kB/s eta 0:00:20
   ---------------- ----------------------- 4.2/10.0 MB 294.4 kB/s eta 0:00:20
   ----------------- ---------------------- 4.5/10.0 MB 304.7 kB/s eta 0:00:19
   ----------------- ---------------------- 4.5/10.0 MB 304.7 kB/s eta 0:00:19
   ----------------- ---------------------- 4.5/10.0 MB 304.7 kB/s eta 0:00:19
   ----------------- ---------------------- 4.5/10.0 MB 304.7 kB/s eta 0:00:19
   ----------------- ---------------------- 4.5/10.0 MB 304.7 kB/s eta 0:00:19
   ----------------- ---------------------- 4.5/10.0 MB 304.7 kB/s eta 0:00:19
   ----------------- ---------------------- 4.5/10.0 MB 304.7 kB/s eta 0:00:19
   ----------------- ---------------------- 4.5/10.0 MB 304.7 kB/s eta 0:00:19
   ------------------ --------------------- 4.7/10.0 MB 287.7 kB/s eta 0:00:19
   ------------------ --------------------- 4.7/10.0 MB 287.7 kB/s eta 0:00:19
   ------------------ --------------------- 4.7/10.0 MB 287.7 kB/s eta 0:00:19
   -------------------- ------------------- 5.0/10.0 MB 294.0 kB/s eta 0:00:17
   -------------------- ------------------- 5.0/10.0 MB 294.0 kB/s eta 0:00:17
   -------------------- ------------------- 5.0/10.0 MB 294.0 kB/s eta 0:00:17
   -------------------- ------------------- 5.0/10.0 MB 294.0 kB/s eta 0:00:17
   -------------------- ------------------- 5.0/10.0 MB 294.0 kB/s eta 0:00:17
   -------------------- ------------------- 5.0/10.0 MB 294.0 kB/s eta 0:00:17
   -------------------- ------------------- 5.0/10.0 MB 294.0 kB/s eta 0:00:17
   -------------------- ------------------- 5.0/10.0 MB 294.0 kB/s eta 0:00:17
   --------------------- ------------------ 5.2/10.0 MB 283.0 kB/s eta 0:00:17
   --------------------- ------------------ 5.2/10.0 MB 283.0 kB/s eta 0:00:17
   ---------------------- ----------------- 5.5/10.0 MB 291.3 kB/s eta 0:00:16
   ---------------------- ----------------- 5.5/10.0 MB 291.3 kB/s eta 0:00:16
   ----------------------- ---------------- 5.8/10.0 MB 299.2 kB/s eta 0:00:14
   ----------------------- ---------------- 5.8/10.0 MB 299.2 kB/s eta 0:00:14
   ------------------------ --------------- 6.0/10.0 MB 306.9 kB/s eta 0:00:13
   ------------------------- -------------- 6.3/10.0 MB 315.6 kB/s eta 0:00:12
   ------------------------- -------------- 6.3/10.0 MB 315.6 kB/s eta 0:00:12
   -------------------------- ------------- 6.6/10.0 MB 323.1 kB/s eta 0:00:11
   --------------------------- ------------ 6.8/10.0 MB 331.5 kB/s eta 0:00:10
   --------------------------- ------------ 6.8/10.0 MB 331.5 kB/s eta 0:00:10
   --------------------------- ------------ 6.8/10.0 MB 331.5 kB/s eta 0:00:10
   --------------------------- ------------ 6.8/10.0 MB 331.5 kB/s eta 0:00:10
   --------------------------- ------------ 6.8/10.0 MB 331.5 kB/s eta 0:00:10
   --------------------------- ------------ 6.8/10.0 MB 331.5 kB/s eta 0:00:10
   ---------------------------- ----------- 7.1/10.0 MB 326.3 kB/s eta 0:00:09
   ---------------------------- ----------- 7.1/10.0 MB 326.3 kB/s eta 0:00:09
   ---------------------------- ----------- 7.1/10.0 MB 326.3 kB/s eta 0:00:09
   ----------------------------- ---------- 7.3/10.0 MB 329.4 kB/s eta 0:00:08
   ----------------------------- ---------- 7.3/10.0 MB 329.4 kB/s eta 0:00:08
   ------------------------------ --------- 7.6/10.0 MB 334.6 kB/s eta 0:00:08
   ------------------------------ --------- 7.6/10.0 MB 334.6 kB/s eta 0:00:08
   ------------------------------- -------- 7.9/10.0 MB 338.9 kB/s eta 0:00:07
   ------------------------------- -------- 7.9/10.0 MB 338.9 kB/s eta 0:00:07
   -------------------------------- ------- 8.1/10.0 MB 344.7 kB/s eta 0:00:06
   -------------------------------- ------- 8.1/10.0 MB 344.7 kB/s eta 0:00:06
   -------------------------------- ------- 8.1/10.0 MB 344.7 kB/s eta 0:00:06
   --------------------------------- ------ 8.4/10.0 MB 347.8 kB/s eta 0:00:05
   --------------------------------- ------ 8.4/10.0 MB 347.8 kB/s eta 0:00:05
   ---------------------------------- ----- 8.7/10.0 MB 351.5 kB/s eta 0:00:04
   ---------------------------------- ----- 8.7/10.0 MB 351.5 kB/s eta 0:00:04
   ---------------------------------- ----- 8.7/10.0 MB 351.5 kB/s eta 0:00:04
   ---------------------------------- ----- 8.7/10.0 MB 351.5 kB/s eta 0:00:04
   ---------------------------------- ----- 8.7/10.0 MB 351.5 kB/s eta 0:00:04
   ---------------------------------- ----- 8.7/10.0 MB 351.5 kB/s eta 0:00:04
   ----------------------------------- ---- 8.9/10.0 MB 346.1 kB/s eta 0:00:04
   ----------------------------------- ---- 8.9/10.0 MB 346.1 kB/s eta 0:00:04
   ----------------------------------- ---- 8.9/10.0 MB 346.1 kB/s eta 0:00:04
   ------------------------------------ --- 9.2/10.0 MB 348.0 kB/s eta 0:00:03
   ------------------------------------ --- 9.2/10.0 MB 348.0 kB/s eta 0:00:03
   ------------------------------------- -- 9.4/10.0 MB 352.1 kB/s eta 0:00:02
   ------------------------------------- -- 9.4/10.0 MB 352.1 kB/s eta 0:00:02
   -------------------------------------- - 9.7/10.0 MB 357.3 kB/s eta 0:00:01
   -------------------------------------- - 9.7/10.0 MB 357.3 kB/s eta 0:00:01
   -------------------------------------- - 9.7/10.0 MB 357.3 kB/s eta 0:00:01
   ---------------------------------------- 10.0/10.0 MB 358.9 kB/s  0:00:27
Downloading numpy-2.5.1-cp314-cp314-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 508.8 kB/s eta 0:00:24
   - -------------------------------------- 0.5/12.6 MB 508.8 kB/s eta 0:00:24
   - -------------------------------------- 0.5/12.6 MB 508.8 kB/s eta 0:00:24
   - -------------------------------------- 0.5/12.6 MB 508.8 kB/s eta 0:00:24
   - -------------------------------------- 0.5/12.6 MB 508.8 kB/s eta 0:00:24
   -- ------------------------------------- 0.8/12.6 MB 339.2 kB/s eta 0:00:35
   -- ------------------------------------- 0.8/12.6 MB 339.2 kB/s eta 0:00:35
   --- ------------------------------------ 1.0/12.6 MB 398.2 kB/s eta 0:00:29
   --- ------------------------------------ 1.0/12.6 MB 398.2 kB/s eta 0:00:29
   ---- ----------------------------------- 1.3/12.6 MB 419.5 kB/s eta 0:00:27
   ---- ----------------------------------- 1.3/12.6 MB 419.5 kB/s eta 0:00:27
   ---- ----------------------------------- 1.3/12.6 MB 419.5 kB/s eta 0:00:27
   ----- ---------------------------------- 1.6/12.6 MB 420.7 kB/s eta 0:00:27
   ----- ---------------------------------- 1.8/12.6 MB 468.4 kB/s eta 0:00:23
   ----- ---------------------------------- 1.8/12.6 MB 468.4 kB/s eta 0:00:23
   ------ --------------------------------- 2.1/12.6 MB 494.5 kB/s eta 0:00:22
   ------- -------------------------------- 2.4/12.6 MB 523.9 kB/s eta 0:00:20
   ------- -------------------------------- 2.4/12.6 MB 523.9 kB/s eta 0:00:20
   ------- -------------------------------- 2.4/12.6 MB 523.9 kB/s eta 0:00:20
   ------- -------------------------------- 2.4/12.6 MB 523.9 kB/s eta 0:00:20
   -------- ------------------------------- 2.6/12.6 MB 494.8 kB/s eta 0:00:21
   -------- ------------------------------- 2.6/12.6 MB 494.8 kB/s eta 0:00:21
   --------- ------------------------------ 2.9/12.6 MB 506.0 kB/s eta 0:00:20
   --------- ------------------------------ 2.9/12.6 MB 506.0 kB/s eta 0:00:20
   --------- ------------------------------ 2.9/12.6 MB 506.0 kB/s eta 0:00:20
   ---------- ----------------------------- 3.1/12.6 MB 510.5 kB/s eta 0:00:19
   ---------- ----------------------------- 3.4/12.6 MB 520.6 kB/s eta 0:00:18
   ---------- ----------------------------- 3.4/12.6 MB 520.6 kB/s eta 0:00:18
   ----------- ---------------------------- 3.7/12.6 MB 537.5 kB/s eta 0:00:17
   ----------- ---------------------------- 3.7/12.6 MB 537.5 kB/s eta 0:00:17
   ------------ --------------------------- 3.9/12.6 MB 546.0 kB/s eta 0:00:16
   ------------- -------------------------- 4.2/12.6 MB 558.1 kB/s eta 0:00:15
   ------------- -------------------------- 4.2/12.6 MB 558.1 kB/s eta 0:00:15
   -------------- ------------------------- 4.5/12.6 MB 571.5 kB/s eta 0:00:15
   --------------- ------------------------ 4.7/12.6 MB 587.3 kB/s eta 0:00:14
   --------------- ------------------------ 5.0/12.6 MB 601.9 kB/s eta 0:00:13
   ---------------- ----------------------- 5.2/12.6 MB 615.5 kB/s eta 0:00:12
   ---------------- ----------------------- 5.2/12.6 MB 615.5 kB/s eta 0:00:12
   ----------------- ---------------------- 5.5/12.6 MB 626.3 kB/s eta 0:00:12
   ------------------ --------------------- 5.8/12.6 MB 636.8 kB/s eta 0:00:11
   ------------------- -------------------- 6.0/12.6 MB 652.4 kB/s eta 0:00:11
   -------------------- ------------------- 6.3/12.6 MB 665.8 kB/s eta 0:00:10
   -------------------- ------------------- 6.6/12.6 MB 679.3 kB/s eta 0:00:09
   --------------------- ------------------ 6.8/12.6 MB 692.6 kB/s eta 0:00:09
   ---------------------- ----------------- 7.1/12.6 MB 705.2 kB/s eta 0:00:08
   ----------------------- ---------------- 7.3/12.6 MB 716.0 kB/s eta 0:00:08
   ------------------------ --------------- 7.6/12.6 MB 724.3 kB/s eta 0:00:07
   ------------------------ --------------- 7.6/12.6 MB 724.3 kB/s eta 0:00:07
   ------------------------ --------------- 7.6/12.6 MB 724.3 kB/s eta 0:00:07
   ------------------------ --------------- 7.6/12.6 MB 724.3 kB/s eta 0:00:07
   ------------------------ --------------- 7.6/12.6 MB 724.3 kB/s eta 0:00:07
   ------------------------ --------------- 7.6/12.6 MB 724.3 kB/s eta 0:00:07
   ------------------------- -------------- 7.9/12.6 MB 679.2 kB/s eta 0:00:07
   ------------------------- -------------- 7.9/12.6 MB 679.2 kB/s eta 0:00:07
   ------------------------- -------------- 7.9/12.6 MB 679.2 kB/s eta 0:00:07
   ------------------------- -------------- 7.9/12.6 MB 679.2 kB/s eta 0:00:07
   ------------------------- -------------- 8.1/12.6 MB 646.2 kB/s eta 0:00:07
   ------------------------- -------------- 8.1/12.6 MB 646.2 kB/s eta 0:00:07
   ------------------------- -------------- 8.1/12.6 MB 646.2 kB/s eta 0:00:07
   ------------------------- -------------- 8.1/12.6 MB 646.2 kB/s eta 0:00:07
   -------------------------- ------------- 8.4/12.6 MB 631.2 kB/s eta 0:00:07
   -------------------------- ------------- 8.4/12.6 MB 631.2 kB/s eta 0:00:07
   --------------------------- ------------ 8.7/12.6 MB 631.1 kB/s eta 0:00:07
   --------------------------- ------------ 8.7/12.6 MB 631.1 kB/s eta 0:00:07
   --------------------------- ------------ 8.7/12.6 MB 631.1 kB/s eta 0:00:07
   ---------------------------- ----------- 8.9/12.6 MB 624.2 kB/s eta 0:00:06
   ----------------------------- ---------- 9.2/12.6 MB 626.4 kB/s eta 0:00:06
   ----------------------------- ---------- 9.2/12.6 MB 626.4 kB/s eta 0:00:06
   ------------------------------ --------- 9.4/12.6 MB 629.8 kB/s eta 0:00:05
   ------------------------------ --------- 9.4/12.6 MB 629.8 kB/s eta 0:00:05
   ------------------------------ --------- 9.7/12.6 MB 632.3 kB/s eta 0:00:05
   ------------------------------ --------- 9.7/12.6 MB 632.3 kB/s eta 0:00:05
   ------------------------------ --------- 9.7/12.6 MB 632.3 kB/s eta 0:00:05
   ------------------------------ --------- 9.7/12.6 MB 632.3 kB/s eta 0:00:05
   ------------------------------ --------- 9.7/12.6 MB 632.3 kB/s eta 0:00:05
   ------------------------------ --------- 9.7/12.6 MB 632.3 kB/s eta 0:00:05
   ------------------------------ --------- 9.7/12.6 MB 632.3 kB/s eta 0:00:05
   ------------------------------ --------- 9.7/12.6 MB 632.3 kB/s eta 0:00:05
   ------------------------------ --------- 9.7/12.6 MB 632.3 kB/s eta 0:00:05
   ------------------------------ --------- 9.7/12.6 MB 632.3 kB/s eta 0:00:05
   ------------------------------ --------- 9.7/12.6 MB 632.3 kB/s eta 0:00:05
   ------------------------------ --------- 9.7/12.6 MB 632.3 kB/s eta 0:00:05
   ------------------------------ --------- 9.7/12.6 MB 632.3 kB/s eta 0:00:05
   ------------------------------ --------- 9.7/12.6 MB 632.3 kB/s eta 0:00:05
   ------------------------------ --------- 9.7/12.6 MB 632.3 kB/s eta 0:00:05
   ------------------------------- -------- 10.0/12.6 MB 540.5 kB/s eta 0:00:05
   ------------------------------- -------- 10.0/12.6 MB 540.5 kB/s eta 0:00:05
   ------------------------------- -------- 10.0/12.6 MB 540.5 kB/s eta 0:00:05
   -------------------------------- ------- 10.2/12.6 MB 531.7 kB/s eta 0:00:05
   -------------------------------- ------- 10.2/12.6 MB 531.7 kB/s eta 0:00:05
   --------------------------------- ------ 10.5/12.6 MB 534.6 kB/s eta 0:00:04
   --------------------------------- ------ 10.5/12.6 MB 534.6 kB/s eta 0:00:04
   ---------------------------------- ----- 10.7/12.6 MB 540.1 kB/s eta 0:00:04

In [187]:
import pandas as pd

In [190]:
data=[10.5,11.2,9.8,None,11.5,None]
df=pd.DataFrame(data)
df

      0
0  10.5
1  11.2
2   9.8
3   NaN
4  11.5
5   NaN

In [191]:
df.fillna(df.mean(), inplace=True)
df[0].tolist()

[10.5, 11.2, 9.8, 10.75, 11.5, 10.75]

In [192]:
df

       0
0  10.50
1  11.20
2   9.80
3  10.75
4  11.50
5  10.75